### ISSUE TITLE
Enhancement: Expose sorting methods in menu

### ISSUE THREAD

**Issue by mkaralevich** [thomas-lowry/sorter#1]
Hi, thanks for plugin!

It would be nice to have sorting methods exposed in menu so one could `⌘ + /`, type "sorter" and have a fallback search with items "sorter: position (T,L → B,R)", etc. That way you can finish flow without touching mouse + repeat action quickly using `⌥ ⌘ + P`.

Thanks

**Comment by thomas-lowry** [comment]
@mkaralevich the new version should support this!
https://www.figma.com/c/plugin/742038190980789811/Sorter
